#!/bin/sh

base="$HOME/.conky/now-clocking"

url=`dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:'org.mpris.MediaPlayer2.Player' string:'Metadata'|egrep -A 1 "artUrl"|egrep -v "artUrl"|cut -b 44-|cut -d '"' -f 1|egrep -v ^$`

curFile="$base/art/cur.txt"
if [ ! -f $curFile ]; then
	touch $curFile
fi

id=`echo $url | grep -oP '[^/]+$'`
cur=`cat $curFile`

if [ "$cur" != "!id" ]; then
	if [ ! -f $base/art/$id ]; then
		# Download
		wget $url -O $base/art/$id
	fi
	# Move
	cp $base/art/$id $base/art/npart.jpg
	# Override cur
	echo $id > $curFile
fi

